# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PolygonDivider
								 A QGIS plugin
 Divides polygons into smaller 'squareish' polygons of a specified size
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
							  -------------------
		begin                : 2020-02-24
		git sha              : $Format:%H$
		copyright            : (C) 2023 Lune Geographic
		email                : info@lunegeographic.co.uk
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/

 * This script divides a polygon into squareish sections of a specified size
 *
 * TODO'S:
 *  - Where / how often should we calculate the desired area?
 *  - Need to re-think how to deal with problems in subdivision - perhaps need to calculate all subdivisions then save all at once so we can roll back?
 *  - This could be run in multiple parallel tasks (all strips calculated then divided up into processes to get squareish sections from them)
 *
 * @author jonnyhuck
 *
"""

import os.path
import traceback
from uuid import uuid4
from qgis import processing
from qgis.utils import iface
from qgis.PyQt.QtGui import QIcon
from .pyroots import Brentq, Brenth
from qgis.PyQt.QtWidgets import QAction, QFileDialog
from .polygon_divider_dialog import PolygonDividerDialog
from processing.gui.AlgorithmExecutor import execute_in_place
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, QMetaType
from qgis.core import Qgis, QgsGeometry, QgsPoint, QgsField, QgsTask, QgsFeature, QgsVectorLayer, \
	QgsVectorFileWriter, QgsProject, QgsMessageLog, QgsApplication

class BrentError(Exception):
	"""
	* Simple class used for exceptions from Brent's Method.
	"""
	def __init__(self, value):
		self.value = value
	def __str__(self):
		return repr(self.value)


# Global label for task messages
MESSAGE_CATEGORY = 'POLYGON DIVIDER'


''' ROTATION FUNCTIONS (used to rotate the dataset so that the cutlines are at an angle to the axes) '''


def rotate_layer(input_path: str, degrees: float, rotation_center: str = None, output_path: str = 'TEMPORARY_OUTPUT'):
	"""
	* Rotate the input dataset by the given number of degrees around the given center point,
	*  returning the result as a new (in-memory by default) layer
	"""
	# run the rotation algorithm from the processing toolbox and return the resulting layer
	return processing.run("native:rotatefeatures",
		{
			'INPUT': input_path,
			'ANGLE': degrees,
			'ANCHOR': rotation_center,
			'OUTPUT': output_path
		}
	)['OUTPUT']


def rotate_layer_in_place(input_layer, degrees: float, rotation_center: str = None):
	"""
	* Rotate the given layer by the given number of degrees around the given center point,
	*  editing the layer directly (used to rotate the divided output back again)
	"""
	# get the rotation algorithm from the processing registry
	alg = QgsApplication.instance().processingRegistry().algorithmById("native:rotatefeatures")

	# run it against the layer's own features (edits the layer in place)
	execute_in_place(alg,
		{
			'INPUT': input_layer,
			'ANGLE': degrees,
			'ANCHOR': rotation_center
		}
	)


class PolygonDividerTask(QgsTask):
	"""
	* Class extending QgsTask to handle on different thread
	"""

	''' INHERITED CLASS FUNCTIONS '''

	def __init__(self, layer, outFilePath, target_area, absorb_flag, direction, tolerance, rotation_in_degrees, solver_name='brentq'):
		"""
		* Initialise the thread
		"""
		# call constructor for QsgThread
		super().__init__("Polygon Division", QgsTask.Flag.CanCancel)

		# load arguments into class variables
		self.layer = layer
		self.outFilePath = outFilePath
		self.target_area = target_area
		self.absorb_flag = absorb_flag
		self.direction = direction
		self.tolerance = tolerance
		self.exception = None
		self.rotation_in_degrees = rotation_in_degrees

		# select the root-finding solver class based on the user's choice in the dialog
		self.solver_class = Brenth if solver_name == 'brenth' else Brentq

		# count of polygons that could not be divided (reported to the user on completion)
		self.n_failed = 0

		# point of rotation - the center of the layer's extent, so that the data rotates 'in place'
		#  (rotating around the CRS origin would swing far-from-origin coordinates through very large
		#  intermediate values, inviting floating point precision problems)
		center = layer.extent().center()
		self.rotation_center = f"{center.x()},{center.y()}"
		self.rotation_success = False

	def finished(self, result):
		"""
		* This function is automatically called when the task has completed (successfully or not).
		* It called from the main thread, so it's safe to do GUI operations and raise Python exceptions here.
		* result is the return value from self.run.
		"""
		# success
		if result:

			# Notify User
			QgsMessageLog.logMessage('Polygon Division completed', MESSAGE_CATEGORY, Qgis.MessageLevel.Success)
			iface.messageBar().pushMessage("Success!", 'Polygon Division completed', level=Qgis.MessageLevel.Success, duration=3)

			# warn the user if any polygons could not be divided
			if self.n_failed > 0:
				QgsMessageLog.logMessage(f'{self.n_failed} polygon(s) could not be divided after trying all four directions and were written undivided', MESSAGE_CATEGORY, Qgis.MessageLevel.Warning)
				iface.messageBar().pushMessage("Warning:", f'{self.n_failed} polygon(s) could not be divided and were written undivided', level=Qgis.MessageLevel.Warning, duration=6)

			# finally, open the resulting file and return it
			layer = iface.addVectorLayer(self.outFilePath, 'Divided Polygon', "ogr")

			# alert if invalid (NB: don't raise here - this runs on the main thread, so an
			#  unhandled exception could take the whole of QGIS down with it)
			if layer is None or not layer.isValid():
				QgsMessageLog.logMessage('Output Dataset Invalid', MESSAGE_CATEGORY, Qgis.MessageLevel.Critical)
				iface.messageBar().pushMessage("Error:", 'Output Dataset Invalid', level=Qgis.MessageLevel.Critical)

		# failure
		else:
			# failed without exception (user cancel)
			if self.exception is None:
				QgsMessageLog.logMessage('Polygon Division exited without exception', MESSAGE_CATEGORY, Qgis.MessageLevel.Warning)
				iface.messageBar().pushMessage("Warning:", 'Polygon Division Cancelled', level=Qgis.MessageLevel.Warning, duration=3)

			# failed with exception (report it, including the stack trace to the log for debugging)
			else:
				stack_trace = ''.join(traceback.format_exception(type(self.exception), self.exception, self.exception.__traceback__))
				QgsMessageLog.logMessage(f'Polygon Division Exception: {stack_trace}', MESSAGE_CATEGORY, Qgis.MessageLevel.Critical)
				iface.messageBar().pushMessage("Error:", f'Polygon Division Failed: {str(self.exception)}', level=Qgis.MessageLevel.Critical)


	def cancel(self):
		"""
		* This function is called when the task is cancelled
		"""

		# log that the task was cancelled
		QgsMessageLog.logMessage("Polygon Division was manually cancelled by the user", MESSAGE_CATEGORY, Qgis.MessageLevel.Info)

		# run the cancel method from QgsTask
		super().cancel()


	''' OPERATIONAL FUNCTIONS '''


	def brent(self, xa, xb, xtol, ftol, max_iter, geom, fixedCoord1, fixedCoord2, targetArea, horizontal, forward):
		"""
		* Brent's Method, as implemented in the bundled pyroots library (Brentq or Brenth,
		*  as selected by the user in the dialog).
		*
		* - xa is the lower bracket of the interval of the solution we search.
		* - xb is the upper bracket of the interval of the solution we search.
		* - xtol is the minimum	 permitted width (in map units) of the interval before we give up.
		* - ftol is the required precision of the solution.
		* - max_iter is the maximum allowed number of iterations.
		* - geom is the geometry we are dividing.
		* - fixedCoord1 is the the first coordinate in the fixed dimension.
		* - fixedCoord2 is the the second coordinate in the fixed dimension.
		* - targetArea is the desired area of the section to cut off geom.
		* - horizontal or vertical cut - True / False respectively
		* - forward (left-right or bottom top) cut or backward (right-left or top-bottom) - True / False respectively
		*
		* Returns the optimal coordinate in the variable dimension, or None on failure (in which
		*  case self.exception is set to a BrentError describing what went wrong).
		"""

		# construct the user-selected solver (pyroots' epsilon is the equivalent of ftol, xtol is the same)
		solver = self.solver_class(epsilon=ftol, xtol=xtol, max_iter=max_iter, raise_on_fail=False)

		# run the solver against the area difference function (f), passing on the geometry arguments
		result = solver(self.f, xa, xb, geom, fixedCoord1, fixedCoord2, targetArea, horizontal, forward)

		# if the solver converged, return the root that it found
		if result.converged:
			return result.x0

		# running out of iterations isn't as good, but the result seems generally fine, so return it anyway
		if result.msg == "Exceeded max iterations.":
			return result.x0	# NB: increasing the number of iterations doesn't seem to get any closer

		# otherwise, record the failure as an exception and return None to signal it to the caller
		self.exception = BrentError(result.msg)
		return None


	def splitPoly(self, polygon, splitter, horizontal, forward):
		"""
		* Split a Polygon with a LineString
		* Returns exactly two polygons notionally referred to as being 'left' and 'right' of the cutline.
		* The relationship between them is that the 'right' polygon (the chip) is notionally cut from the 'left' one (the potato).
		"""

		# need to take a deep copy for the incoming polygon, as splitGeometry edits it directly...
		poly = QgsGeometry(polygon)

		# parse splitter into required objects
		splitter = [QgsPoint(splitter[0][0], splitter[0][1]), QgsPoint(splitter[1][0], splitter[1][1])]

		# split poly (polygon) by splitter (line)
		# http://gis.stackexchange.com/questions/114414/cannot-split-a-line-using-qgsgeometry-splitgeometry-in-qgis
		res, polys, topolist = poly.splitGeometry(splitter, False)

		# add poly (which might be a multipolygon) to the polys array
		if poly.isMultipart():
			# if the feature is a multipolygon, explode into separate polygons for individual processing
			multiGeom = poly.asMultiPolygon()
			for i in multiGeom:
				polys.append(QgsGeometry().fromPolygonXY(i))
		else:
			# ...OR load the feature into a list of one (it may be extended in the course of splitting if we create noncontiguous offcuts) and loop through it
			polys.append(poly)

		''' SORT RIGHT, LEFT, RESIDUAL '''

		# verify that it worked and that more than one polygon was returned
		if res == 0 and len(polys) >1:
			if forward: ### from bottom left
				if horizontal:	## cut from the bottom

					# left is the top one
					maxy = float('-inf')
					for i in range(len(polys)):
						p = polys[i].boundingBox().yMaximum()
						if p > maxy:
							maxy = p
							maxyi = i
					left = polys.pop(maxyi)

					# right is the bottom one
					miny = float('inf')
					for i in range(len(polys)):
						p = polys[i].boundingBox().yMinimum()
						if p < miny:
							miny = p
							minyi = i
						elif p == miny:		# if there is a tie for which is the rightest, get the rightest in the other dimension
							if polys[i].boundingBox().xMinimum() < polys[minyi].boundingBox().xMinimum():	# left
								minyi = i
					right = polys.pop(minyi)

				else:	## cutting from the left

					# left is the rightest one
					maxx = float('-inf')
					for i in range(len(polys)):
						p = polys[i].boundingBox().xMaximum()
						if p > maxx:
							maxx = p
							maxxi = i
					left = polys.pop(maxxi)

					# right is the leftest one
					minx = float('inf')
					for i in range(len(polys)):
						p = polys[i].boundingBox().xMinimum()
						if p < minx:
							minx = p
							minxi = i
						elif p == minx:		# if there is a tie for which is the rightest, get the rightest in the other dimension
							if polys[i].boundingBox().yMinimum() < polys[minxi].boundingBox().yMinimum():	# bottom
								minxi = i
					right = polys.pop(minxi)

			else:	### cut from top / right (forward_flag is false)

				if horizontal:	## cut from the top

					# left is the bottom one
					miny = float('inf')
					for i in range(len(polys)):
						p = polys[i].boundingBox().yMinimum()
						if p < miny:
							miny = p
							minyi = i
					left = polys.pop(minyi)

					# right is the top one
					maxy = float('-inf')
					for i in range(len(polys)):
						p = polys[i].boundingBox().yMaximum()
						if p > maxy:
							maxy = p
							maxyi = i
						elif p == maxy:		# if there is a tie for which is the rightest, get the rightest in the other dimension
							if polys[i].boundingBox().xMaximum() > polys[maxyi].boundingBox().xMaximum():
								maxyi = i
					right = polys.pop(maxyi)

				else:	## cutting from the right

					# left is the leftest one
					minx = float('inf')
					for i in range(len(polys)):
						p = polys[i].boundingBox().xMinimum()
						if p < minx:
							minx = p
							minxi = i
					left = polys.pop(minxi)

					# right is the rightest one
					maxx = float('-inf')
					for i in range(len(polys)):
						p = polys[i].boundingBox().xMaximum()
						if p > maxx:
							maxx = p
							maxxi = i
						elif p == maxx:		# if there is a tie for which is the rightest, get the rightest in the other dimension
							if polys[i].boundingBox().yMaximum() > polys[maxxi].boundingBox().yMaximum():
								maxxi = i
					right = polys.pop(maxxi)

			# work out if any remaining polygons are contiguous with left or not
			contiguous = []
			noncontiguous = []
			if len(polys) > 0:
				for j in polys:
					if left.touches(j):
						contiguous.append(j)
					else:
						noncontiguous.append(j)

				# join all contiguous parts back to left
				if len(contiguous) > 0:
					contiguous += [left]
					left = QgsGeometry.unaryUnion(contiguous)

			# return the two sections (left is the potato, right is the chip...), plus any noncontiguous polygons
			return left, right, noncontiguous
		else:
			# log the error and raise an exception - this is caught by the caller (either to try another
			#  cut direction, or by the catch-all in run() so that the user gets to see the message)
			QgsMessageLog.logMessage(f"FAIL: Polygon division failed ({res})", MESSAGE_CATEGORY, Qgis.MessageLevel.Critical)
			raise Exception(f"Failed to split polygon (splitGeometry returned {res})")


	def getSliceArea(self,sliceCoord, poly, fixedCoord1, fixedCoord2, horizontal, forward):
		"""
		* Splits a polygon to a defined distance from the minimum value for the selected dimension and
		*  returns the area of the resultng polygon
		"""

		# construct a list of points representing a line by which to split the polygon
		if horizontal:
			splitter = [(fixedCoord1, sliceCoord), (fixedCoord2, sliceCoord)] # horizontal split
		else:
			splitter = [(sliceCoord, fixedCoord1), (sliceCoord, fixedCoord2)] # vertical split

		# split the polygon
		left, right, residual = self.splitPoly(poly, splitter, horizontal, forward)

		# return the area of the bit you cut off
		return right.area()


	def f(self,sliceCoord, poly, fixedCoord1, fixedCoord2, targetArea, horizontal, forward):
		"""
		* Split a Polygon with a LineString, returning the area of the polygon to the right of the split
		* returns the area of the polygon on the right of the splitter line
		"""

		# return the difference between the resulting polygon area (right of the line) and the desired area
		return self.getSliceArea(sliceCoord, poly, fixedCoord1, fixedCoord2, horizontal, forward) - targetArea


	''' THE MAIN FUNCTION FOR THE TASK'''


	def run(self):
		"""
		* Actually do the processing
		"""
		layer = None

		# first 'try' to rotate the layer
		# rotate only if rotation number set, if 0, no need to rotate
		if self.rotation_in_degrees:
			try:
				layer = rotate_layer(
					input_path=self.layer.source(),
					degrees=self.rotation_in_degrees,
					rotation_center=self.rotation_center
				)
				layer.updateExtents(True)
			except Exception as e:
				# log the problem so that the user knows (processing continues with the un-rotated original)
				QgsMessageLog.logMessage(f"Rotation failed ({e}), continuing without rotation", MESSAGE_CATEGORY, Qgis.MessageLevel.Warning)
				layer = None

		# if the rotation was set, but fails
		# continue with the original file, else set rotated layer
		if layer is not None:
			self.layer = layer
			# if all went well, set the rotation flag to rotate again at the end
			self.rotation_success = True

		# This whole function is in a catch-all try statement to avoid QGIS burying exceptions.
		try:

			# setup for progress bar ad message
			QgsMessageLog.logMessage("Started Polygon Division", MESSAGE_CATEGORY, Qgis.MessageLevel.Info)

			# get data out of object
			layer = self.layer
			outFilePath = self.outFilePath
			target_area = self.target_area
			absorb_flag = self.absorb_flag
			direction = self.direction

			# validation that the file is projected
			if layer.crs().isGeographic():
				QgsMessageLog.logMessage("Whoops! The Polygon Divider requires a projected dataset - please save a copy with a projected CRS and try again.", MESSAGE_CATEGORY, Qgis.MessageLevel.Critical)
				self.exception = Exception("Whoops! The Polygon Divider requires a projected dataset - please save a copy with a projected CRS and try again.")
				return False

			# used to control progress bar (only send signal for an increase)
			currProgress = 0
			self.setProgress(currProgress)

			# initial settings
			t = self.tolerance   # initial tolerance for function rooting - this is flexible now it has been divorced from the buffer
			buffer = 1e-5        # this is the buffer to ensure that an intersection occurs
			# NB: this buffer value started causing splitGeometry to fail when it was 1e-6 - check this if it happens again

			# set the direction (horizontal or vertical)
			if direction < 2:
				horizontal_flag = True
			else:
				horizontal_flag = False

			# True = cut from bottom / left, False = cut from top / right
			if (direction == 0 or direction == 2):
				forward_flag = True
			else:
				forward_flag = False

			# get fields from the input shapefile
			fieldList = self.layer.fields()

			# add new fields for this tool, checking first that they don't already exist in the input data
			#  (if one does, it is re-used and its values are overwritten in the output, so warn the user)
			for field in [QgsField('POLY_ID', QMetaType.Type.Int), QgsField('UNIQUE_ID', QMetaType.Type.QString),
				QgsField('AREA', QMetaType.Type.Double), QgsField('POINTX', QMetaType.Type.Double),
				QgsField('POINTY', QMetaType.Type.Double)]:
				if fieldList.lookupField(field.name()) == -1:
					fieldList.append(field)
				else:
					QgsMessageLog.logMessage(f"The field {field.name()} already exists in the input data - its values will be overwritten in the output", MESSAGE_CATEGORY, Qgis.MessageLevel.Warning)

			# create a new shapefile to write the results to
			transform_context = QgsProject.instance().transformContext()
			save_options = QgsVectorFileWriter.SaveVectorOptions()
			# .shp and .gpkg are supported
			save_options.driverName = "ESRI Shapefile" if outFilePath.endswith('.shp') else "GPKG"
			save_options.fileEncoding = "UTF-8"

			# in a GeoPackage, a column called 'fid' is the primary key, so if the input data has a field with
			#  that name then every output piece would inherit the same value and all but the first would be
			#  rejected as duplicate keys - so tell OGR to use a different (unused) name for the primary key,
			#  which turns the inherited field back into an ordinary attribute
			if save_options.driverName == "GPKG" and fieldList.lookupField('fid') != -1:
				fidName = 'ogc_fid'
				while fieldList.lookupField(fidName) != -1:
					fidName += '_'
				save_options.layerOptions = [f'FID={fidName}']
				QgsMessageLog.logMessage(f"The input data has a 'fid' field, so the GeoPackage primary key will be called {fidName}", MESSAGE_CATEGORY, Qgis.MessageLevel.Info)
			writer = QgsVectorFileWriter.create(outFilePath, fieldList, Qgis.WkbType.Polygon, layer.crs(), transform_context, save_options)
			if writer.hasError() != QgsVectorFileWriter.WriterError.NoError:
				QgsMessageLog.logMessage(f"Error when creating {save_options.driverName}: {writer.errorMessage()}", MESSAGE_CATEGORY, Qgis.MessageLevel.Critical)


			# define this to ensure that it's global
			subfeatures = []

			# init feature counter (for ID's) and a counter for any features that fail to write
			j = 0
			self.n_write_errors = 0

			# how many sections will we have (for progress bar)
			totalArea = 0
			for feat in layer.getFeatures():
				totalArea += feat.geometry().area()
			totalDivisions = max(totalArea // target_area, 1)	# needs to be at least 1, to avoid dividing by zero when updating progress

			# helper to write a geometry to the output file with the correct schema and attributes
			#  (avoids repeating the same block for pieces, offcuts and un-dividable polygons)
			def writeFeature(geometry, currAttributes):

				# we need to write to the counters in the enclosing scope
				nonlocal j, currProgress

				# make a feature with the right schema
				fet = QgsFeature()
				fet.setFields(fieldList)

				# populate inherited attributes
				for a in range(len(currAttributes)):
					fet[a] = currAttributes[a]

				# calculate representative point
				pt = geometry.pointOnSurface().asPoint()

				# populate new attributes
				fet.setAttribute('POLY_ID', j)
				fet.setAttribute('UNIQUE_ID', str(uuid4()))
				fet.setAttribute('AREA', geometry.area())
				fet.setAttribute('POINTX', pt[0])
				fet.setAttribute('POINTY', pt[1])

				# add the geometry to the feature
				fet.setGeometry(geometry)

				# write the feature to the out file, checking that it actually worked (a failure here would
				#  otherwise be silent, resulting in missing features in the output)
				if not writer.addFeature(fet):
					QgsMessageLog.logMessage(f"Failed to write a feature to the output file: {writer.errorMessage()}", MESSAGE_CATEGORY, Qgis.MessageLevel.Critical)
					self.n_write_errors += 1

				# increment feature counter
				j += 1

				# update progress bar if required
				if int((j*1.0) / totalDivisions * 100) > currProgress:
					currProgress = int((j*1.0) / totalDivisions * 100)
					self.setProgress(currProgress)

			# check if you've been killed
			if self.isCanceled():
				return False

			# loop through all of the features in the input data
			for feat in layer.getFeatures():

				# verify that it is a polygon (this covers all of the polygon and multipolygon variants, including Z / M)
				if feat.geometry().type() == Qgis.GeometryType.Polygon:

					# get the attributes to write out
					currAttributes = feat.attributes()

					# extract the geometry and sort out self intersections etc. with a buffer of 0m
					bufferedPolygon = feat.geometry().buffer(0, 15)

					# if the buffer came back as None, skip
					if bufferedPolygon is None:
						QgsMessageLog.logMessage("A polygon could not be buffered by QGIS, ignoring", MESSAGE_CATEGORY, Qgis.MessageLevel.Info)
						continue

					# make multipolygon into list of polygons...
					subfeatures = []
					if bufferedPolygon.isMultipart():
						multiGeom = QgsGeometry()
						multiGeom = bufferedPolygon.asMultiPolygon()
						for i in multiGeom:
							subfeatures.append(QgsGeometry().fromPolygonXY(i))
					else:
						# ...OR load the feature into a list of one (it may be extended in the course of splitting if we create noncontiguous offcuts) and loop through it
						subfeatures.append(bufferedPolygon)

					#loop through the geometries
					for poly in subfeatures:

						# flag to record if we had to give up dividing this polygon (so we don't write it out twice)
						gaveUp = False

						# how many polygons are we going to have to chop off?
						nPolygons = int(poly.area() // target_area)

						# (needs to be at least 1...)
						if nPolygons == 0:
							nPolygons = 1

						# adjust the targetArea to reflect absorption if required
						if absorb_flag:

							# there is no offcut when absorbing, so the remainder has to be spread between the pieces -
							#  use one more piece if that brings the piece size closer to the target (this keeps the
							#  pieces as close as possible to the specified size, and also stops a piece that came up
							#  fractionally short - e.g. a residual from a cut that was made to within the tolerance -
							#  from being under-counted and absorbed into a double-sized neighbour)
							if abs(poly.area() / (nPolygons + 1) - target_area) < abs(poly.area() / nPolygons - target_area):
								nPolygons += 1

							# spreading the remainder equally between the pieces is the same as dividing the area equally
							targetArea = poly.area() / nPolygons
						else:
							targetArea = target_area

						# work out the size of a square with area = targetArea if required
						sq = targetArea**0.5

						# work out when to stop dividing: if absorbing, the remainder is by construction exactly one
						#  targetArea, so use a 50% margin that accumulated tolerance error cannot trip (otherwise we
						#  can end up cutting off a sliver as an 'extra' polygon); if not absorbing, anything more
						#  than the tolerance bigger than one piece still needs dividing
						if absorb_flag:
							minRemainder = targetArea * 1.5
						else:
							minRemainder = targetArea + t

						# until there is no more dividing to do...
						while poly.area() > minRemainder:

							# the bounds of the polygon are used to construct the cutline for each attempted direction
							boundsR = poly.boundingBox()
							bounds = [boundsR.xMinimum(), boundsR.yMinimum(), boundsR.xMaximum(), boundsR.yMaximum()]

							# get interval and fixed coordinates (buffer otherwise there won't be an intersection between polygon and cutline!)
							if horizontal_flag:
								interval = bounds[1] + buffer, bounds[3] - buffer
								fixedCoords = bounds[0], bounds[2]
							else:
								interval = bounds[0] + buffer, bounds[2] - buffer
								fixedCoords = bounds[1], bounds[3]

							# is the interval larger than the required square? (We know the required area is > target+t because of the while statement)
							if (interval[1]-interval[0]) > sq:

								'''now use Brent's method to find the optimal coordinate in the variable dimension (e.g. the y coord for a horizontal
									cut), trying each of the four cut directions in turn (current direction first) until one of them works'''

								# init the result so that we can tell whether any of the directions succeeded
								result = None

								# try each direction: the current one first, then reversed movement, then each way along the flipped cutline
								for horizontal, forward in [(horizontal_flag, forward_flag), (horizontal_flag, not forward_flag),
									(not horizontal_flag, forward_flag), (not horizontal_flag, not forward_flag)]:

									# get interval and fixed coordinates for this cut direction (buffer otherwise there won't be an intersection between polygon and cutline!)
									if horizontal:
										interval = bounds[1] + buffer, bounds[3] - buffer
										fixedCoords = bounds[0], bounds[2]
									else:
										interval = bounds[0] + buffer, bounds[2] - buffer
										fixedCoords = bounds[1], bounds[3]

									# the attempt might fail outright (e.g. the cutline misses the polygon), which just counts as a failed direction
									try:

										# is the interval larger than the required square in this direction?
										if (interval[1]-interval[0]) > sq:

											# this is the resulting area of a slice the width of sq from the polygon
											if forward:
												sqArea = self.getSliceArea(interval[0] + sq - buffer, poly, fixedCoords[0], fixedCoords[1], horizontal, forward)	# cutting from bottom/left
											else:
												sqArea = self.getSliceArea(interval[1] - sq + buffer, poly, fixedCoords[0], fixedCoords[1], horizontal, forward)	# cutting from top/right

											# what is the nearest number of subdivisions of targetArea that could be extracted from that slice?
											nSubdivisions = int(round(sqArea / targetArea))

											# if the answer is 0, make it 1...
											if nSubdivisions == 0:
												nSubdivisions = 1

										# the interval is too narrow for a square-width strip in this direction, so just try to cut off a single piece
										else:
											nSubdivisions = 1

										# how big must the target area be to support this many subdivisions?
										initialTargetArea = nSubdivisions * targetArea

										# try to zero the equation
										result = self.brent(interval[0], interval[1], 1e-6, t, 500, poly, fixedCoords[0], fixedCoords[1], initialTargetArea, horizontal, forward)

									# treat a hard failure just the same as a failure to converge - move on to the next direction
									except Exception as e:
										self.exception = BrentError(str(e))
										result = None

									# if it worked then stop trying directions, otherwise log the failure and go around again
									if result is not None:
										break
									else:
										QgsMessageLog.logMessage(f"{self.exception.value}: trying next direction (Division)", MESSAGE_CATEGORY, Qgis.MessageLevel.Warning)

								# if none of the four directions worked then we have to give up on this polygon
								if result is None:

									''' WRITE THE UNSPLITTABLE POLYGON TO THE SHAPEFILE ANYWAY (SO THAT NO AREA IS LOST) '''
									writeFeature(poly, currAttributes)

									# log that there was a problem and count it for the final report to the user
									QgsMessageLog.logMessage("There was an un-dividable polygon in this dataset (all four directions failed).", MESSAGE_CATEGORY, Qgis.MessageLevel.Warning)
									self.n_failed += 1

									# clear the stored exception, as we are carrying on rather than failing
									self.exception = None

									# give up on this polygon (it has been written already) and move on to the next one, hopefully with more luck!
									gaveUp = True
									break

								# the successful direction becomes the preferred direction for subsequent cuts
								horizontal_flag, forward_flag = horizontal, forward

								# create the desired cutline as lists of QgsPoints
								if horizontal_flag:
									line = [(fixedCoords[0], result), (fixedCoords[1], result)] # horizontal split
								else:
									line = [(result, fixedCoords[0]), (result, fixedCoords[1])] # vertical split

								# calculate the resulting polygons - poly will be sliced again, initialSlice will be subdivided
								poly, initialSlice, residuals = self.splitPoly(poly, line, horizontal_flag, forward_flag)

								# put the residuals in the list to be processed
								subfeatures += residuals

								# the strip contains nSubdivisions pieces, so the remainder after the cuts below is the final piece
								nCuts = nSubdivisions - 1

							# bounds not bigger than sq, so no division necessary, just subdivide this last one directly (nothing will happen if it can't be subdivided)
							else:
								# set the remainder of the polygon as the final slice, and poly to an empty polygon
								initialSlice = poly
								poly = QgsGeometry.fromPolygonXY([[]])

								# work out how many cuts we need to make in this final slice
								if absorb_flag:

									# absorbing: cut the slice into however many equal pieces (at least 1) is closest to the target size...
									nPieces = int(initialSlice.area() // targetArea)
									if nPieces == 0:
										nPieces = 1
									if abs(initialSlice.area() / (nPieces + 1) - targetArea) < abs(initialSlice.area() / nPieces - targetArea):
										nPieces += 1

									# ...and the remainder after the cuts is simply the final piece
									nCuts = nPieces - 1
								else:

									# not absorbing: cut off as many full pieces of targetArea as will fit (at least 1)...
									nFull = int(initialSlice.area() // targetArea)
									if nFull == 0:
										nFull = 1

									# ...and if what is left over is bigger than the tolerance then it is a true offcut (which needs its own
									#  cut), otherwise the sub-tolerance sliver is simply absorbed into the final piece (rather than being
									#  written out as a sliver polygon, which would make the number of polygons different to that specified)
									if initialSlice.area() - (nFull * targetArea) > t:
										nCuts = nFull
									else:
										nCuts = nFull - 1

							# flag to record if we had to give up subdividing this slice (so we don't write it out twice)
							sliceGaveUp = False

							#...then divide that into sections of targetArea
							for k in range(nCuts):	# nCuts pieces are chopped off, plus whatever remains at the end

								'''use Brent's method to find the optimal coordinate in the variable dimension (e.g. the y coord for a horizontal
									cut), trying each of the four cut directions in turn (perpendicular to the strip first) until one of them works'''

								# init the result so that we can tell whether any of the directions succeeded
								sliceResult = None

								# try each direction: perpendicular to the strip first (otherwise we would get long thin strips, not squares)
								for sliceHorizontal, sliceForward in [(not horizontal_flag, forward_flag), (not horizontal_flag, not forward_flag),
									(horizontal_flag, forward_flag), (horizontal_flag, not forward_flag)]:

									# the bounds are used for the interval
									sliceBoundsR = initialSlice.boundingBox()
									sliceBounds = [sliceBoundsR.xMinimum(), sliceBoundsR.yMinimum(), sliceBoundsR.xMaximum(), sliceBoundsR.yMaximum()]

									# get interval and fixed coordinates for this cut direction (buffer otherwise there won't be an intersection between polygon and cutline!)
									if sliceHorizontal:
										sliceInterval = sliceBounds[1] + buffer, sliceBounds[3] - buffer
										sliceFixedCoords = sliceBounds[0], sliceBounds[2]
									else:
										sliceInterval = sliceBounds[0] + buffer, sliceBounds[2] - buffer
										sliceFixedCoords = sliceBounds[1], sliceBounds[3]

									# the attempt might fail outright (e.g. the cutline misses the polygon), which just counts as a failed direction
									try:

										# try to zero the equation
										sliceResult = self.brent(sliceInterval[0], sliceInterval[1], 1e-6, t, 500, initialSlice, sliceFixedCoords[0], sliceFixedCoords[1], targetArea, sliceHorizontal, sliceForward)

									# treat a hard failure just the same as a failure to converge - move on to the next direction
									except Exception as e:
										self.exception = BrentError(str(e))
										sliceResult = None

									# if it worked then stop trying directions, otherwise log the failure and go around again
									if sliceResult is not None:
										break
									else:
										QgsMessageLog.logMessage(f"{self.exception.value}: trying next direction (Subdivision)", MESSAGE_CATEGORY, Qgis.MessageLevel.Warning)

								# if none of the four directions worked then we have to give up on this slice
								if sliceResult is None:

									''' WRITE THE UNSPLITTABLE SLICE TO THE SHAPEFILE ANYWAY (SO THAT NO AREA IS LOST) '''
									writeFeature(initialSlice, currAttributes)

									# log that there was a problem and count it for the final report to the user
									QgsMessageLog.logMessage("There was an un-subdividable slice in this dataset (all four directions failed).", MESSAGE_CATEGORY, Qgis.MessageLevel.Warning)
									self.n_failed += 1

									# clear the stored exception, as we are carrying on rather than failing
									self.exception = None

									# give up on this slice (it has been written already) and move on, hopefully with more luck!
									sliceGaveUp = True
									break

								# the successful movement direction becomes the preferred direction for subsequent cuts
								forward_flag = sliceForward

								# create the desired cutline as lists of QgsPoints
								if sliceHorizontal:
									sliceLine = [(sliceFixedCoords[0], sliceResult), (sliceFixedCoords[1], sliceResult)]	# horizontal split
								else:
									sliceLine = [(sliceResult, sliceFixedCoords[0]), (sliceResult, sliceFixedCoords[1])]	# vertical split

								# calculate the resulting polygons - initialSlice becomes left (to be chopped again)
								initialSlice, right, residuals = self.splitPoly(initialSlice, sliceLine, sliceHorizontal, sliceForward)

								# put the residuals in the list to be processed
								subfeatures += residuals

								''' WRITE THE PIECE TO THE SHAPEFILE '''
								writeFeature(right, currAttributes)

							## WRITE THE REMAINDER OF THE SLICE (THE FINAL PIECE, OR THE OFFCUT IF NOT ABSORBING) TO SHAPEFILE
							#  (unless we gave up on the slice above, in which case it has been written already)
							if not sliceGaveUp:
								writeFeature(initialSlice, currAttributes)

						## WRITE THE REMAINDER FROM DIVISION (THE FINAL PIECE, OR THE OFFCUT IF NOT ABSORBING) TO SHAPEFILE
						#  (unless we gave up on the polygon, or there is nothing left but a sub-tolerance sliver)
						if not gaveUp and not poly.isEmpty() and poly.area() > t:
							writeFeature(poly, currAttributes)
				else:
					QgsMessageLog.logMessage("Whoops! That dataset isn't polygons!", MESSAGE_CATEGORY, Qgis.MessageLevel.Critical)
					self.exception = Exception("Whoops! That dataset isn't polygons!")
					return False

			if self.isCanceled():
				return False

			# finally, open the resulting file and return it
			# but first close the driver for writing
			del writer

			layer = QgsVectorLayer(outFilePath, 'Divided Polygon', 'ogr')

			if layer.isValid():
				# rotate the layer if the flag was set
				if self.rotation_success:
					layer.updateExtents(True)
					rotate_layer_in_place(
						input_layer=layer,
						degrees=-self.rotation_in_degrees,
						rotation_center=self.rotation_center
					)
					# NB: extent calculation fails (but no error is thrown in QGIS 3.28) when updating shapefile, but everything is alright when layer is saved as a GPKG
					# it is not a critical error, layer is still valid and geometry has no errors
					# just QGIS's 'Zoom to Layer(s)' might not center the layer correctly, as it depends on extent
					layer.updateExtents(True)
					layer.commitChanges()

					del layer
				# return success
				return True
			else:
				self.exception = Exception("Output Dataset Invalid")
				return False

		# catch-all to prevent exceptions being buried by QGIS
		except Exception as e:
			self.exception = e
			return False

class PolygonDivider:
	"""QGIS Plugin Implementation."""

	def __init__(self, iface):
		"""Constructor.

		:param iface: An interface instance that will be passed to this class
			which provides the hook by which you can manipulate the QGIS
			application at run time.
		:type iface: QgsInterface
		"""
		# Save reference to the QGIS interface
		self.iface = iface
		# initialize plugin directory
		self.plugin_dir = os.path.dirname(__file__)
		# initialize locale (falling back to English if no locale has been set)
		locale = (QSettings().value('locale/userLocale') or 'en')[0:2]
		locale_path = os.path.join(
			self.plugin_dir,
			'i18n',
			'PolygonDivider_{}.qm'.format(locale))

		if os.path.exists(locale_path):
			self.translator = QTranslator()
			self.translator.load(locale_path)
			QCoreApplication.installTranslator(self.translator)

		# Declare instance attributes
		self.actions = []
		self.menu = self.tr(u'&Polygon Divider')

		# JJH: declare task manager to handle the backcround task
		self.tm = QgsApplication.taskManager()

		# Check if plugin was started the first time in current QGIS session
		# Must be set in initGui() to survive plugin reloads
		self.first_start = None


	# noinspection PyMethodMayBeStatic
	def tr(self, message):
		"""Get the translation for a string using Qt translation API.

		We implement this ourselves since we do not inherit QObject.

		:param message: String for translation.
		:type message: str, QString

		:returns: Translated version of message.
		:rtype: QString
		"""
		# noinspection PyTypeChecker,PyArgumentList,PyCallByClass
		return QCoreApplication.translate('PolygonDivider', message)


	def add_action(
		self,
		icon_path,
		text,
		callback,
		enabled_flag=True,
		add_to_menu=True,
		add_to_toolbar=True,
		status_tip=None,
		whats_this=None,
		parent=None):
		"""Add a toolbar icon to the toolbar.

		:param icon_path: Path to the icon for this action. Can be a resource
			path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
		:type icon_path: str

		:param text: Text that should be shown in menu items for this action.
		:type text: str

		:param callback: Function to be called when the action is triggered.
		:type callback: function

		:param enabled_flag: A flag indicating if the action should be enabled
			by default. Defaults to True.
		:type enabled_flag: bool

		:param add_to_menu: Flag indicating whether the action should also
			be added to the menu. Defaults to True.
		:type add_to_menu: bool

		:param add_to_toolbar: Flag indicating whether the action should also
			be added to the toolbar. Defaults to True.
		:type add_to_toolbar: bool

		:param status_tip: Optional text to show in a popup when mouse pointer
			hovers over the action.
		:type status_tip: str

		:param parent: Parent widget for the new action. Defaults None.
		:type parent: QWidget

		:param whats_this: Optional text to show in the status bar when the
			mouse pointer hovers over the action.

		:returns: The action that was created. Note that the action is also
			added to self.actions list.
		:rtype: QAction
		"""

		icon = QIcon(icon_path)
		action = QAction(icon, text, parent)
		action.triggered.connect(callback)
		action.setEnabled(enabled_flag)

		if status_tip is not None:
			action.setStatusTip(status_tip)

		if whats_this is not None:
			action.setWhatsThis(whats_this)

		if add_to_toolbar:
			# Adds plugin icon to Plugins toolbar
			self.iface.addToolBarIcon(action)

		if add_to_menu:
			self.iface.addPluginToVectorMenu(
				self.menu,
				action)

		self.actions.append(action)

		return action


	def select_output_file(self):
		"""
		* Open file browser
		"""

		# get filename from dialog
		filename = QFileDialog.getSaveFileName(self.dlg, "Select output file ","", "Shapefiles (*.shp);;GeoPackage (*.gpkg)")[0]

		# verify that a name was selected
		if filename != "":

			# clear previous value
			self.dlg.lineEdit_2.clear()

			# put the result in the text box on the dialog
			self.dlg.lineEdit_2.setText(filename)


	def radio_handler(self):
		"""
		* Respond to radio button toggle by setting which text box is active and
		*  setting the flag
		"""
		# see which is checked and enable / disable the text boxes accordingly
		if self.dlg.radioButton_2.isChecked():
			self.dlg.lineEdit.setDisabled(True)
			self.dlg.lineEdit_3.setEnabled(True)

			# absorbing offcuts makes no sense when dividing into an exact number of polygons, so
			#  un-tick and disable the option (it is also enforced when the settings are read in run)
			self.dlg.checkBox.setChecked(False)
			self.dlg.checkBox.setDisabled(True)
		elif self.dlg.radioButton.isChecked():
			self.dlg.lineEdit.setEnabled(True)
			self.dlg.lineEdit_3.setDisabled(True)

			# re-enable the absorb offcuts option
			self.dlg.checkBox.setEnabled(True)


	def initGui(self):
		"""Create the menu entries and toolbar icons inside the QGIS GUI."""

		# the icon is loaded directly from the plugin directory (rather than from a compiled Qt
		#  resource file, which would need to be built differently for Qt5 and Qt6)
		icon_path = os.path.join(self.plugin_dir, 'icon.png')
		self.add_action(
			icon_path,
			text=self.tr(u'Polygon Divider'),
			callback=self.run,
			parent=self.iface.mainWindow())

		# will be set False in run()
		self.first_start = True


	def unload(self):
		"""Removes the plugin menu item and icon from QGIS GUI."""
		for action in self.actions:
			self.iface.removePluginVectorMenu(
				self.tr(u'&Polygon Divider'),
				action)
			self.iface.removeToolBarIcon(action)


	def run(self):
		"""
		* Run method that performs all the real work
		"""

		# Create the dialog with elements (after translation) and keep reference
		# Only create GUI ONCE in callback, so that it will only load when the plugin is started
		if self.first_start == True:

			# toggle flag
			self.first_start = False

			# get reference to the dialog object
			self.dlg = PolygonDividerDialog()

			''' THIS SETUP FIRST TIME IT LOADS ONLY '''

			# button listener - launch file browser for output file
			self.dlg.pushButton.clicked.connect(self.select_output_file)

			# radio button listeners - flip enabled field
			self.dlg.radioButton.toggled.connect(self.radio_handler)
			self.dlg.radioButton_2.toggled.connect(self.radio_handler)

		''' THIS SETUP EVERY TIME IT LOADS '''

		# populate comboBox with the active layers
		self.dlg.comboBox.clear()	# need to clear here or it will add them all again every time the dialog is opened
		layers = QgsProject.instance().layerTreeRoot().findLayers()
		self.dlg.comboBox.addItems([layer.name() for layer in layers])

		# populate comboBox_2 with the possible directions
		self.dlg.comboBox_2.clear() # need to clear here or it will add them all again every time the dialog is opened
		self.dlg.comboBox_2.addItems(['left to right', 'right to left', 'bottom to top', 'top to bottom'])

		# populate comboBoxSolver with the available root-finding algorithms
		self.dlg.comboBoxSolver.clear() # need to clear here or it will add them all again every time the dialog is opened
		self.dlg.comboBoxSolver.addItems(['brentq', 'brenth'])

		# show the dialog
		self.dlg.show()

		# Run the dialog event loop (NB: not the old exec_(), which no longer exists under Qt6)
		result = self.dlg.exec()

		# See if OK was pressed
		if result:

			''' VALIDATE THE FORM INPUTS '''

			# collect descriptions of any problems so that they can all be reported to the user at once
			problems = []

			# there must be a layer selected...
			inFile = None
			if not layers or self.dlg.comboBox.currentIndex() < 0:
				problems.append("no input layer is selected")
			else:
				# ...and it must be a polygon vector layer
				inFile = layers[self.dlg.comboBox.currentIndex()].layer()
				if not isinstance(inFile, QgsVectorLayer):
					problems.append("the input layer is not a vector layer")
				elif inFile.geometryType() != Qgis.GeometryType.Polygon:
					problems.append("the input layer is not a polygon layer")

			# the output file must be set, and must be a shapefile or a geopackage
			outFilePath = self.dlg.lineEdit_2.text().strip()
			if not (outFilePath.endswith('.shp') or outFilePath.endswith('.gpkg')):
				problems.append("the output file must be a .shp or .gpkg file")

			# the target area must be a positive number (only used if that option is selected)
			targetArea = 0
			if self.dlg.radioButton.isChecked():
				try:
					targetArea = float(self.dlg.lineEdit.text())
					if targetArea <= 0:
						problems.append("the target area must be greater than 0")
				except ValueError:
					problems.append("the target area must be a number")

			# the number of divisions must be a positive whole number (only used if that option is selected)
			num_divisions = 1
			if self.dlg.radioButton_2.isChecked():
				try:
					num_divisions = int(self.dlg.lineEdit_3.text())
					if num_divisions <= 0:
						problems.append("the number of divisions must be greater than 0")
				except ValueError:
					problems.append("the number of divisions must be a whole number")

			# the tolerance must be a positive number
			tolerance = 0
			try:
				tolerance = float(self.dlg.lineEdit_4.text())
				if tolerance <= 0:
					problems.append("the tolerance must be greater than 0")
			except ValueError:
				problems.append("the tolerance must be a number")

			# report any problems to the user and give up (they can re-open the dialog and try again)
			if problems:
				self.iface.messageBar().pushMessage("Error:", f"Polygon Divider could not run: {'; '.join(problems)}.", level=Qgis.MessageLevel.Critical)
				return

			''' RUN THE TOOL '''

			# get the remaining user settings (these cannot be invalid)
			absorbFlag = self.dlg.checkBox.isChecked()
			direction = self.dlg.comboBox_2.currentIndex()
			solverName = self.dlg.comboBoxSolver.currentText()
			rotation_in_degrees = float(self.dlg.doubleSpinBoxRotation.value())

			# invert rotation direction (so we are effectively rotating the cutline, not the polygon)
			#  NB: the modulo keeps 0 as 0, so that no rotation is attempted when none was requested
			rotation_in_degrees = (360 - rotation_in_degrees) % 360

			# if the user has selected number of divisions option, calculate target area
			if self.dlg.radioButton_2.isChecked():

				# sum the area of all features in the input layer
				total_area = 0
				for feature in inFile.getFeatures():
					total_area += feature.geometry().area()

				# calculate target area for each division
				targetArea = total_area / float(num_divisions)

				# turn off absorb flag for this case (also enforced in the UI by radio_handler)
				absorbFlag = False

			# launch the task
			self.tm.addTask(PolygonDividerTask(inFile, outFilePath, targetArea, absorbFlag, direction, tolerance, rotation_in_degrees, solverName))
